// Copyright (c) 2025 Michele Tavella <meeghele@proton.me>
// Licensed under the MIT License. See LICENSE file for details.

/**
 * @file struct_types.h
 * @brief Struct definitions for mini-ccstatus
 */

#ifndef MCCS_TYPES_STRUCT_H
#define MCCS_TYPES_STRUCT_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include "constants.h"

/**
 * Storage buffers for parsed JSON string values
 * These buffers own the actual string data copied from JSON
 */
struct mccs_buffers {
  char buf_model_name[BUF_MODEL_NAME_SIZE]; ///< Model display name (e.g. "Claude 3.5 Sonnet")
  char buf_model_id[BUF_MODEL_ID_SIZE];     ///< Full model identifier with version suffix
  char buf_cwd[BUF_PATH_SIZE];              ///< Current working directory path
  char buf_project[BUF_PATH_SIZE];          ///< Project root directory path
  char buf_version[BUF_VERSION_SIZE];       ///< Claude Code version string
};

/**
 * String reference pointers for efficient access
 * Points either into mccs_buffers or to UNKNOWN_VALUE constant
 */
struct mccs_string_refs {
  const char *model_name;  ///< Points to model name or UNKNOWN_VALUE
  const char *model_id;    ///< Points to model ID or UNKNOWN_VALUE
  const char *cwd;         ///< Points to current directory or UNKNOWN_VALUE
  const char *project_dir; ///< Points to project directory or UNKNOWN_VALUE
  const char *version;     ///< Points to version string or UNKNOWN_VALUE
};

/**
 * Numeric counters and metrics from Claude Code session
 * All metrics are cumulative from session start
 */
struct mccs_counters {
  double cost_usd;          ///< Total cost in USD (NaN if unavailable)
  uint32_t duration_ms;     ///< Total session wall-clock time in milliseconds
  uint32_t api_ms;          ///< Total API request time in milliseconds
  uint32_t lines_added;     ///< Cumulative lines added (from git diff)
  uint32_t lines_removed;   ///< Cumulative lines removed (from git diff)
  bool exceeds_200k_tokens; ///< Whether session exceeded 200k token limit
};

/**
 * Complete status information for a Claude Code session
 * Combines string storage, references, and numeric counters
 */
struct mccs_status {
  struct mccs_buffers buffers;         ///< String storage
  struct mccs_string_refs string_refs; ///< Pointers into buffers
  struct mccs_counters counters;       ///< Numeric metrics
};

/**
 * Token usage counts across different categories
 * Matches Claude API's token usage structure
 */
struct token_counts {
  uint64_t input_tokens;          ///< Tokens sent to model (prompt)
  uint64_t output_tokens;         ///< Tokens generated by model (completion)
  uint64_t cache_creation_tokens; ///< Tokens used to create prompt cache
  uint64_t cache_read_tokens;     ///< Tokens read from prompt cache
  uint64_t total_tokens;          ///< Sum of all token categories
};

/**
 * Cached token statistics to avoid re-parsing large files
 * Tracks file sizes to detect changes and invalidate cache
 * Stores raw token counts; percentages are derived during rendering
 */
struct token_cache {
  uint32_t magic;                       ///< Magic number for cache validation (CACHE_MAGIC)
  int64_t last_update_time;             ///< Last cache update (seconds since epoch)
  char session_id[BUF_SESSION_ID_SIZE]; ///< Session ID for cache validation
  char project_dir[BUF_PATH_SIZE];      ///< Project directory for cache validation
  struct token_counts session_tokens;   ///< Total tokens across entire session
  struct token_counts context_tokens;   ///< Context window tokens (last message)
  size_t transcript_file_size;          ///< Transcript file size at last parse
};

/**
 * Command-line options for controlling output features
 * All options default to false unless specified
 */
struct cli_options {
  bool show_token_breakdown;        ///< Show detailed token breakdown (--token-breakdown)
  bool show_context_tokens;         ///< Show context window percentage (--context-tokens)
  bool show_session_tokens;         ///< Show session total tokens (--session-tokens)
  bool show_cache_efficiency;       ///< Show cache efficiency ratio (--cache-efficiency)
  bool show_api_time_ratio;         ///< Show API time vs total time ratio (--api-time-ratio)
  bool show_lines_ratio;            ///< Show lines added vs removed ratio (--lines-ratio)
  bool show_input_output_ratio;     ///< Show input vs output tokens ratio (--input-output-ratio)
  bool show_cache_write_read_ratio; ///< Show cache write vs read tokens ratio (--cache-write-read-ratio)
  bool clamp_percentages;           ///< Clamp percentages to 100% max (--clamping)
  bool show_all;                    ///< Enable all token features (--all)
  bool no_color;                    ///< Disable ANSI color output (--no-color)
  bool verbose;                     ///< Show field labels in status line (--verbose)
  bool hide_token_breakdown;        ///< Hide token breakdown line (--hide-breakdown)
  bool simple_status_line;          ///< Show simplified main status line (--simple)
};

/**
 * File paths extracted from JSON for token tracking
 * Used to locate session and transcript files
 */
struct mccs_paths {
  char session_id[BUF_SESSION_ID_SIZE];           ///< Unique session identifier
  char transcript_path[BUF_TRANSCRIPT_PATH_SIZE]; ///< Path to JSONL transcript file
};

#endif /* MCCS_TYPES_STRUCT_H */
